title: "YetiApps Support"
description: "Support and FAQs for the Intentsify app."
baseurl: "" # Keep blank unless hosting in a subdirectory
url: "https://support.yetimonstah.com/" # Replace with your live site URL

# Theme configuration
theme: jekyll-theme-cayman
markdown: kramdown
permalink: pretty
include:
  - assets/css
